<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $citys = [
            'Águeda, Aveiro, Portugal',
            'Albergaria-a-Velha, Aveiro, Portugal',
            'Anadia, Aveiro, Portugal',
            'Arouca, Aveiro, Portugal',
            'Aveiro, Aveiro, Portugal',
            'Castelo de Paiva, Aveiro, Portugal',
            'Espinho, Aveiro, Portugal',
            'Estarreja, Aveiro, Portugal',
            'Ílhavo, Aveiro, Portugal',
            'Mealhada, Aveiro, Portugal',
            'Murtosa, Aveiro, Portugal',
            'Oliveira de Azeméis, Aveiro, Portugal',
            'Oliveira do Bairro, Aveiro, Portugal',
            'Ovar, Aveiro, Portugal',
            'Santa Maria da Feira, Aveiro, Portugal',
            'São João da Madeira, Aveiro, Portugal',
            'Sever do Vouga, Aveiro, Portugal',
            'Vagos, Aveiro, Portugal',
            'Vale de Cambra, Aveiro, Portugal',
            'Aljustrel, Beja, Portugal',
            'Almodôvar, Beja, Portugal',
            'Alvito, Beja, Portugal',
            'Barrancos, Beja, Portugal',
            'Beja, Beja, Portugal',
            'Castro Verde, Beja, Portugal',
            'Cuba, Beja, Portugal',
            'Ferreira do Alentejo, Beja, Portugal',
            'Mértola, Beja, Portugal',
            'Moura, Beja, Portugal',
            'Odemira, Beja, Portugal',
            'Ourique, Beja, Portugal',
            'Serpa, Beja, Portugal',
            'Vidigueira, Beja, Portugal',
            'Amares, Braga, Portugal',
            'Barcelos, Braga, Portugal',
            'Braga, Braga, Portugal',
            'Cabeceiras de Basto, Braga, Portugal',
            'Celorico de Basto, Braga, Portugal',
            'Esposende, Braga, Portugal',
            'Fafe, Braga, Portugal',
            'Guimarães, Braga, Portugal',
            'Póvoa de Lanhoso, Braga, Portugal',
            'Terras de Bouro, Braga, Portugal',
            'Vieira do Minho, Braga, Portugal',
            'Vila Nova de Famalicão, Braga, Portugal',
            'Vila Verde, Braga, Portugal',
            'Vizela, Braga, Portugal',
            'Alfândega da Fé, Bragança, Portugal',
            'Bragança, Bragança, Portugal',
            'Carrazeda de Ansiães, Bragança, Portugal',
            'Freixo de Espada à Cinta, Bragança, Portugal',
            'Macedo de Cavaleiros, Bragança, Portugal',
            'Miranda do Douro, Bragança, Portugal',
            'Mirandela, Bragança, Portugal',
            'Mogadouro, Bragança, Portugal',
            'Torre de Moncorvo, Bragança, Portugal',
            'Vila Flor, Bragança, Portugal',
            'Vimioso, Bragança, Portugal',
            'Vinhais, Bragança, Portugal',
            'Belmonte, Castelo Branco, Portugal',
            'Castelo Branco, Castelo Branco, Portugal',
            'Covilhã, Castelo Branco, Portugal',
            'Fundão, Castelo Branco, Portugal',
            'Idanha-a-Nova, Castelo Branco, Portugal',
            'Oleiros, Castelo Branco, Portugal',
            'Penamacor, Castelo Branco, Portugal',
            'Proença-a-Nova, Castelo Branco, Portugal',
            'Sertã, Castelo Branco, Portugal',
            'Vila de Rei, Castelo Branco, Portugal',
            'Vila Velha de Ródão, Castelo Branco, Portugal',
            'Arganil, Coimbra, Portugal',
            'Cantanhede, Coimbra, Portugal',
            'Coimbra, Coimbra, Portugal',
            'Condeixa-a-Nova, Coimbra, Portugal',
            'Figueira da Foz, Coimbra, Portugal',
            'Góis, Coimbra, Portugal',
            'Lousã, Coimbra, Portugal',
            'Mealhada, Coimbra, Portugal',
            'Miranda do Corvo, Coimbra, Portugal',
            'Montemor-o-Velho, Coimbra, Portugal',
            'Oliveira do Hospital, Coimbra, Portugal',
            'Pampilhosa da Serra, Coimbra, Portugal',
            'Penacova, Coimbra, Portugal',
            'Penela, Coimbra, Portugal',
            'Soure, Coimbra, Portugal',
            'Tábua, Coimbra, Portugal',
            'Vila Nova de Poiares, Coimbra, Portugal',
            'Borba, Évora, Portugal',
            'Estremoz, Évora, Portugal',
            'Évora, Évora, Portugal',
            'Montemor-o-Novo, Évora, Portugal',
            'Mora, Évora, Portugal',
            'Mourão, Évora, Portugal',
            'Portel, Évora, Portugal',
            'Redondo, Évora, Portugal',
            'Reguengos de Monsaraz, Évora, Portugal',
            'Vendas Novas, Évora, Portugal',
            'Viana do Alentejo, Évora, Portugal',
            'Vila Viçosa, Évora, Portugal',
            'Albufeira, Faro, Portugal',
            'Alcoutim, Faro, Portugal',
            'Aljezur, Faro, Portugal',
            'Castro Marim, Faro, Portugal',
            'Faro, Faro, Portugal',
            'Lagoa, Faro, Portugal',
            'Lagos, Faro, Portugal',
            'Loulé, Faro, Portugal',
            'Monchique, Faro, Portugal',
            'Olhão, Faro, Portugal',
            'Portimão, Faro, Portugal',
            'São Brás de Alportel, Faro, Portugal',
            'Silves, Faro, Portugal',
            'Tavira, Faro, Portugal',
            'Vila do Bispo, Faro, Portugal',
            'Vila Real de Santo António, Faro, Portugal',
            'Aguiar da Beira, Guarda, Portugal',
            'Almeida, Guarda, Portugal',
            'Celorico da Beira, Guarda, Portugal',
            'Figueira de Castelo Rodrigo, Guarda, Portugal',
            'Fornos de Algodres, Guarda, Portugal',
            'Gouveia, Guarda, Portugal',
            'Guarda, Guarda, Portugal',
            'Manteigas, Guarda, Portugal',
            'Mêda, Guarda, Portugal',
            'Pinhel, Guarda, Portugal',
            'Sabugal, Guarda, Portugal',
            'Seia, Guarda, Portugal',
            'Trancoso, Guarda, Portugal',
            'Vila Nova de Foz Côa, Guarda, Portugal',
            'Amarante, Porto, Portugal',
            'Baião, Porto, Portugal',
            'Felgueiras, Porto, Portugal',
            'Gondomar, Porto, Portugal',
            'Lousada, Porto, Portugal',
            'Maia, Porto, Portugal',
            'Marco de Canaveses, Porto, Portugal',
            'Matosinhos, Porto, Portugal',
            'Paços de Ferreira, Porto, Portugal',
            'Paredes, Porto, Portugal',
            'Penafiel, Porto, Portugal',
            'Porto, Porto, Portugal',
            'Póvoa de Varzim, Porto, Portugal',
            'Santo Tirso, Porto, Portugal',
            'Trofa, Porto, Portugal',
            'Valongo, Porto, Portugal',
            'Vila do Conde, Porto, Portugal',
            'Vila Nova de Gaia, Porto, Portugal',
            'Arouca, Aveiro, Portugal',
            'Castelo de Paiva, Aveiro, Portugal',
            'São João da Madeira, Aveiro, Portugal',
            'Sever do Vouga, Aveiro, Portugal',
            'Vagos, Aveiro, Portugal',
            'Vale de Cambra, Aveiro, Portugal',
            'Abrantes, Santarém, Portugal',
            'Alcanena, Santarém, Portugal',
            'Almeirim, Santarém, Portugal',
            'Alpiarça, Santarém, Portugal',
            'Benavente, Santarém, Portugal',
            'Cartaxo, Santarém, Portugal',
            'Chamusca, Santarém, Portugal',
            'Constância, Santarém, Portugal',
            'Coruche, Santarém, Portugal',
            'Entroncamento, Santarém, Portugal',
            'Ferreira do Zêzere, Santarém, Portugal',
            'Golegã, Santarém, Portugal',
            'Mação, Santarém, Portugal',
            'Ourém, Santarém, Portugal',
            'Rio Maior, Santarém, Portugal',
            'Salvaterra de Magos, Santarém, Portugal',
            'Santarém, Santarém, Portugal',
            'Sardoal, Santarém, Portugal',
            'Tomar, Santarém, Portugal',
            'Torres Novas, Santarém, Portugal',
            'Vila Nova da Barquinha, Santarém, Portugal',
            'Alcácer do Sal, Setúbal, Portugal',
            'Alcochete, Setúbal, Portugal',
            'Almada, Setúbal, Portugal',
            'Barreiro, Setúbal, Portugal',
            'Grândola, Setúbal, Portugal',
            'Moita, Setúbal, Portugal',
            'Montijo, Setúbal, Portugal',
            'Palmela, Setúbal, Portugal',
            'Santiago do Cacém, Setúbal, Portugal',
            'Seixal, Setúbal, Portugal',
            'Sesimbra, Setúbal, Portugal',
            'Setúbal, Setúbal, Portugal',
            'Sines, Setúbal, Portugal',
            'Vila Franca de Xira, Lisboa, Portugal',
            'Arruda dos Vinhos, Lisboa, Portugal',
            'Cadaval, Lisboa, Portugal',
            'Cascais, Lisboa, Portugal',
            'Lisboa, Lisboa, Portugal',
            'Loures, Lisboa, Portugal',
            'Mafra, Lisboa, Portugal',
            'Oeiras, Lisboa, Portugal',
            'Sintra, Lisboa, Portugal',
            'Torres Vedras, Lisboa, Portugal',
            'Albergaria-a-Velha, Leiria, Portugal',
            'Alcobaça, Leiria, Portugal',
            'Batalha, Leiria, Portugal',
            'Bombarral, Leiria, Portugal',
            'Caldas da Rainha, Leiria, Portugal',
            'Castanheira de Pêra, Leiria, Portugal',
            'Figueiró dos Vinhos, Leiria, Portugal',
            'Leiria, Leiria, Portugal',
            'Marinha Grande, Leiria, Portugal',
            'Nazaré, Leiria, Portugal',
            'Óbidos, Leiria, Portugal',
            'Pedrógão Grande, Leiria, Portugal',
            'Peniche, Leiria, Portugal',
            'Porto de Mós, Leiria, Portugal',
            'Vieira do Minho, Braga, Portugal',
            'Vila Nova de Famalicão, Braga, Portugal',
            'Vila Verde, Braga, Portugal',
            'Vizela, Braga, Portugal',
            'Alcoutim, Faro, Portugal',
            'Aljezur, Faro, Portugal',
            'Castro Marim, Faro, Portugal',
            'Faro, Faro, Portugal',
            'Lagoa, Faro, Portugal',
            'Lagos, Faro, Portugal',
            'Loulé, Faro, Portugal',
            'Monchique, Faro, Portugal',
            'Olhão, Faro, Portugal',
            'Portimão, Faro, Portugal',
            'São Brás de Alportel, Faro, Portugal',
            'Silves, Faro, Portugal',
            'Tavira, Faro, Portugal',
            'Vila do Bispo, Faro, Portugal',
            'Vila Real de Santo António, Faro, Portugal',
            'Arganil, Coimbra, Portugal',
            'Cantanhede, Coimbra, Portugal',
            'Coimbra, Coimbra, Portugal',
            'Condeixa-a-Nova, Coimbra, Portugal',
            'Figueira da Foz, Coimbra, Portugal',
            'Góis, Coimbra, Portugal',
            'Lousã, Coimbra, Portugal',
            'Mealhada, Coimbra, Portugal',
            'Miranda do Corvo, Coimbra, Portugal',
            'Montemor-o-Velho, Coimbra, Portugal',
            'Oliveira do Hospital, Coimbra, Portugal',
            'Pampilhosa da Serra, Coimbra, Portugal',
            'Penacova, Coimbra, Portugal',
            'Penela, Coimbra, Portugal',
            'Soure, Coimbra, Portugal',
            'Tábua, Coimbra, Portugal',
            'Vila Nova de Poiares, Coimbra, Portugal',
            'Alandroal, Évora, Portugal',
            'Arraiolos, Évora, Portugal',
            'Borba, Évora, Portugal',
            'Estremoz, Évora, Portugal',
            'Évora, Évora, Portugal',
            'Montemor-o-Novo, Évora, Portugal',
            'Mora, Évora, Portugal',
            'Mourão, Évora, Portugal',
            'Portel, Évora, Portugal',
            'Redondo, Évora, Portugal',
            'Reguengos de Monsaraz, Évora, Portugal',
            'Vendas Novas, Évora, Portugal',
            'Viana do Alentejo, Évora, Portugal',
            'Vila Viçosa, Évora, Portugal',
            'Alcanena, Santarém, Portugal',
            'Alter do Chão, Portalegre, Portugal',
            'Ansião, Leiria, Portugal',
            'Armamar, Viseu, Portugal',
            'Arronches, Portalegre, Portugal',
            'Avis, Portalegre, Portugal',
            'Azambuja, Lisboa, Portugal',
            'Batalha, Leiria, Portugal',
            'Borba, Évora, Portugal',
            'Boticas, Vila Real, Portugal',
            'Cabeceiras de Basto, Braga, Portugal',
            'Cadaval, Lisboa, Portugal',
            'Caldas da Rainha, Leiria, Portugal',
            'Campo Maior, Portalegre, Portugal',
            'Carrazeda de Ansiães, Bragança, Portugal',
            'Carregal do Sal, Viseu, Portugal',
            'Cartaxo, Santarém, Portugal',
            'Castanheira de Pera, Leiria, Portugal',
            'Castelo Branco, Castelo Branco, Portugal',
            'Castelo de Paiva, Aveiro, Portugal',
            'Castelo de Vide, Portalegre, Portugal',
            'Castro Daire, Viseu, Portugal',
            'Celorico da Beira, Guarda, Portugal',
            'Celorico de Basto, Braga, Portugal',
            'Chamusca, Santarém, Portugal',
            'Constância, Santarém, Portugal',
            'Coruche, Santarém, Portugal',
            'Cuba, Beja, Portugal',
            'Elvas, Portalegre, Portugal',
            'Entroncamento, Santarém, Portugal',
            'Esposende, Braga, Portugal',
            'Estarreja, Aveiro, Portugal',
            'Estremoz, Évora, Portugal',
            'Figueiró dos Vinhos, Leiria, Portugal',
            'Ferreira do Alentejo, Beja, Portugal',
            'Ferreira do Zêzere, Santarém, Portugal',
            'Freixo de Espada à Cinta, Bragança, Portugal',
            'Fronteira, Portalegre, Portugal',
            'Góis, Coimbra, Portugal',
            'Golegã, Santarém, Portugal',
            'Idanha-a-Nova, Castelo Branco, Portugal',
            'Lagoa, Faro, Portugal',
            'Lagoa, Açores, Portugal',
            'Lamego, Viseu, Portugal',
            'Loures, Lisboa, Portugal',
            'Mafra, Lisboa, Portugal',
            'Marinha Grande, Leiria, Portugal',
            'Miranda do Corvo, Coimbra, Portugal',
            'Miranda do Douro, Bragança, Portugal',
            'Monção, Viana do Castelo, Portugal',
            'Monchique, Faro, Portugal',
            'Montalegre, Vila Real, Portugal',
            'Montemor-o-Novo, Évora, Portugal',
            'Montemor-o-Velho, Coimbra, Portugal',
            'Mortágua, Viseu, Portugal',
            'Moura, Beja, Portugal',
            'Mourão, Évora, Portugal',
            'Nazaré, Leiria, Portugal',
            'Óbidos, Leiria, Portugal',
            'Odemira, Beja, Portugal',
            'Oleiros, Castelo Branco, Portugal',
            'Oliveira do Bairro, Aveiro, Portugal',
            'Pampilhosa da Serra, Coimbra, Portugal',
            'Pedrógão Grande, Leiria, Portugal',
            'Penacova, Coimbra, Portugal',
            'Penafiel, Porto, Portugal',
            'Penamacor, Castelo Branco, Portugal',
            'Peniche, Leiria, Portugal',
            'Ponte de Lima, Viana do Castelo, Portugal',
            'Ponte da Barca, Viana do Castelo, Portugal',
            'Póvoa de Lanhoso, Braga, Portugal',
            'Proença-a-Nova, Castelo Branco, Portugal',
            'Redondo, Évora, Portugal',
            'Reguengos de Monsaraz, Évora, Portugal',
            'Ribeira Brava, Madeira, Portugal',
            'Sabrosa, Vila Real, Portugal',
            'Sabugal, Guarda, Portugal',
            'Salvaterra de Magos, Santarém, Portugal',
            'Santa Maria da Feira, Aveiro, Portugal',
            'Santa Marta de Penaguião, Vila Real, Portugal',
            'Santiago do Cacém, Setúbal, Portugal',
            'Santo Tirso, Porto, Portugal',
            'São Brás de Alportel, Faro, Portugal',
            'São João da Madeira, Aveiro, Portugal',
            'Seixal, Setúbal, Portugal',
            'Serpa, Beja, Portugal',
            'Sesimbra, Setúbal, Portugal',
            'Sines, Setúbal, Portugal',
            'Soure, Coimbra, Portugal',
            'Tabuaço, Viseu, Portugal',
            'Tábua, Coimbra, Portugal',
            'Tarouca, Viseu, Portugal',
            'Tomar, Santarém, Portugal',
            'Torres Novas, Santarém, Portugal',
            'Vila de Rei, Castelo Branco, Portugal',
            'Vila Franca de Xira, Lisboa, Portugal',
            'Vila Nova da Barquinha, Santarém, Portugal',
            'Vila Nova de Gaia, Porto, Portugal',
            'Vila Real, Vila Real, Portugal',
            'Vimioso, Bragança, Portugal',
            'Vinhais, Bragança, Portugal',
            'Vouzela, Viseu, Portugal',
        ];

        foreach ($citys as $city){
            $city = ['name' => $city];
            City::firstOrCreate($city, $city);
        }
    }
}
