services:
    application:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: granatum-api
        container_name: granatum-api
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel_app
        command: bash -c "composer install --optimize-autoloader --no-dev && php artisan key:generate && php-fpm"

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app

networks:
    laravel_app:
        driver: bridge
